### PR TITLE
Fix typo in Alveo U50 Vivado Part Number

### PR DESCRIPTION
**Pull request by C1bergh0st**
typo results in error when compiling for xilinx_u50_gen3x16_xdma_5_202210_1

### CODE REVIEW

**Comment by mariodruiz** [comment]
Thank you! it will take sometime for me to validate this.

**Comment by C1bergh0st** [comment]
Probably also closes Issues #83 and #86

**Comment by mariodruiz** [comment]
Hi @C1bergh0st, did you verify the design functionality?

**Comment by C1bergh0st** [comment]
Design works with provided Notebooks when compiled with this change

**Comment by mariodruiz** [comment]
Thank you for your contribution @C1bergh0st!

**Pull request merged**
